services:     
  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - 8083:80
    environment:
      PMA_ARBITRARY: 1
      #PMA_ABSOLUTE_URI: https://127.0.0.1/phpmyadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8084:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  # pgAdmin4 - PostgreSQL 管理工具
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:8.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@demo.com"
      PGADMIN_DEFAULT_PASSWORD: "oitmis"
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 365
      PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 60
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
    ports:
      - "8086:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/misc/ping"]
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  pgadmin4-data:
    external: false